server:
  port: ${PORT}

cloud:
  config:
    server:
      git:
        uri: https://github.com/amourabarreto/ead-config-server-repo
        default-label: main
        username: ${GIT_USERMANE}
        password: ${GIT_PASSWORD}

ead:
  configServer:
    username: ${CONFIG_SERVER_USERNAME}
    password: ${CONFIG_SERVER_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80

encrypt:
  key: 6w9z$C&F)J@McQfTjWnZr4u7x!A%D*G-KaPdSgUkXp2s5v8y/B?E(H+MbQeThWmY

