server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: ${URI}
          username: ${USERNAME-GIT}
          password: ${PASSWORD--GIT}
#          uri: https://github.com/amourabarreto/ead-config-server-repo
#          username: amourabarreto
#          password: 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

ead:
  configServer:
    username: ${USERNAME}
    password: ${USERNAME}
  serviceRegistry:
    username: ${USERNAME-EUREKA}
    password: ${PASSWORD-EUREKA}

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@${EUREKA-SERVER}:8761/eureka'
      #defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: ead-config-server
