server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amourabarreto/ead-config-server-repo
          default-label: main
          username: amourabarreto
          password: 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

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
