server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: ${URI}
          username: ${USERNAME}
          password: ${PASSWORD}
#          uri: https://github.com/amourabarreto/ead-config-server-repo
#          username: amourabarreto
#          password: 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

eureka:
  client:
    serviceUrl:
      defaultZone: ${URL-EUREKA-SERVER}
  instance:
    prefer-ip-address: true
