server:
  port: 8888


  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/amourabarreto/ead-config-server-repo
          username: amourabarreto
          password: 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

ead:
  configServer:
    username: admin
    password: admin
  serviceRegistry:
    username: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: ead-config-server
