server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: ${URI}
          username: ${USERNAME}
          password: ${PASSWORD}
#          uri: https://github.com/amourabarreto/ead-config-server-repo
#          username: amourabarreto
#          password: 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

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    prefer-ip-address: true
